host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: 后端admin模版api
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Golang-Admin-Boilerpalte Api
  version: "1.0"
paths:
  /admin/users:
    get:
      consumes:
      - application/json
      description: get user list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: users list
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: create user list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: user create
      tags:
      - Users
  /admin/users/{id}:
    delete:
      consumes:
      - application/json
      description: delete user
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: user delete
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: retrieve user
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: user retrieve
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: update user
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: user update
      tags:
      - Users
  /v1/api/articles:
    get:
      consumes:
      - application/json
      description: get user list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: articles list
      tags:
      - Articles
    post:
      consumes:
      - application/json
      description: create user list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: user create
      tags:
      - Articles
  /v1/api/articles/:id:
    delete:
      consumes:
      - application/json
      description: delete user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: user delete
      tags:
      - Articles
    get:
      consumes:
      - application/json
      description: retrieve user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: user retrieve
      tags:
      - Articles
    put:
      consumes:
      - application/json
      description: update user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: user update
      tags:
      - Articles
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
